X-Ray exporter implementation
trace4cats/trace4cats-xray pull request #4
Opened 2022-04-11 14:53 UTC by mrdziuban

Closes trace4cats/trace4cats-xray#3 and trace4cats/trace4cats#118.

Adds initial implementation of an exporter that sends spans to AWS X-Ray. Some notes and questions:

- I'm using `fs2.io.net.DatagramSocket` for writing to the UDP socket, but I'm open to changing this if there's a different library you'd prefer
- X-Ray annotation keys can't have periods, so the keys used by `SemanticTags.<kind|status>Tags` aren't valid. For now I've just replaced periods with underscores
- I'm not sure what the best way is to write tests for the exporter. Unfortunately [LocalStack's X-Ray support](https://docs.localstack.cloud/aws/xray-tracing/) requires LocalStack Pro, so maybe the best option would be to use [fs2's `DatagramSocket#reads`](https://oss.sonatype.org/service/local/repositories/releases/archive/co/fs2/fs2-io_2.13/3.1.0/fs2-io_2.13-3.1.0-javadoc.jar/!/fs2/io/net/DatagramSocket.html#reads:fs2.Stream[F,fs2.io.net.Datagram]) to verify that data is sent properly?

2022-04-11 19:58 UTC, catostrophe commented
Thanks! Will check tomorrow

2022-04-13 07:48 UTC, catostrophe commented
Matt, first of all, thanks for the contribution!

I went through your implementation and found a suspicious logic: you generate and use your own random `xrayTraceId` instead of using the one from `CompletedSpan`. In this case you cannot propagate trace context across service boundaries via [HTTP headers](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader) -- you will lose the link between parts of a distributed trace.

I thought and realized that we had a design flaw in the `model` module. Instead of using `Random[F]` for generating both `TraceId`s and `SpanId`s, we need to introduce new typeclasses, e.g. `TraceIdGen` and `SpanIdGen`. And we shouldn't autoderive them via `Sync` as we do now. Instead, we should propagate `F[_] : TraceIdGen : SpanIdGen` context bound to `SpanContext` to `Span` itself to `EntryPoint`. So that when one creates an `EntryPoint`, they provide instances for `TraceIdGen` and `SpanIdGen`. By default the generators may be based on `Random`, but in case of AWS X-Ray it may have a different implementation via `Clock` + `Random`. `TraceId`/`SpanId` will stay the same byte-arrays (their size may be dynamic). Also their constructors and factory methods must be reviewed and changed.

I did a draft POC in the `trace4cats` repo (not pushed yet), but still need some time to think on ergonomics for end users.

I also need @janstenpickle's opinion on what I am proposing.

2022-04-13 07:50 UTC, catostrophe commented
P.S. And this PR should also include `ToHeaders` instance for X-Ray.

2022-04-13 08:01 UTC, janstenpickle commented
Thank you Matt, this is great!

RE the new typeclasses for ID generation, yes I completely agree. Having specific, derivable typeclasses for this makes a lot of sense.

RE testing: it's a shame that LocalStack doesn't support X-Ray, but I agree with the best effort apporach of listening for the data.

2022-04-13 13:45 UTC, catostrophe commented
I spent some more time thinking on the changes in the `trace4cats` repo. There are a few things that make my first idea not quite viable:
1. Our model implies that `TraceId` is a universal entity that fits _any_ tracing standard t4c integrates with. That is, once generated, a `traceId` must be correct for and exportable to any system, be it OT, Datadog, Zipkin, X-Ray, <_you name it_>.
2. It is `EntryPoint` that creates the root span (and hence generates a `traceId`).
3. Exporters are combinable (there's a `Monoid` instance). That is, a combined `SpanExporter` may send spans to many systems and we don't know to which. `SpanExporter` is passed to the `EntryPoint` factory method.

Given these constraints, if we even try to make generation of TraceId customizable at the level of construction of `EntryPoint`, we can't guarantee that the `SpanExporter` instance passed to it is compatible with this custom TraceId generator.

What we still can do:
1. Make the proposed changes regarding removing the `Random` context bound and introducing `***Gen` typeclasses instead. Add `***Gen` bounds to all higher levels discussed above.
2. Fix the universal traceId internal format as a 16-byte array, as it is now. It can't be of arbitrary size, since it's universal.
3. Provide a `TraceIdGen` instance that generates 16-byte traceIds via `Clock`+`Random` - this will satisfy all existing exporters, since all systems use 16-byte traceIds, including `X-Ray` that just requires first 4 bytes to be epoch time rather than random

It is still not clear, when and how we should provide alternative generators and how to make sure they are compatible with the exporters.

Also, if tomorrow we want to integrate with a tracing system that uses 100-char alphanumeric traceIds, we won't be able to do it, unfortunately.

2022-04-13 14:39 UTC, catostrophe commented
With the proposed changes, the old code written for previously supported systems will be source compatible.

Users of X-Ray will have to import a custom instance to the local scope that will be passed to `EntryPoint.apply`.

2022-04-14 07:14 UTC, catostrophe requested changes

2022-04-14 07:14 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private val nameRegex: Regex = """[^\p{L}0-9 _\.:/%&#=\+\-@]""".r
This and the next val's names are a bit misleading. Could we name them differently? My suggestion is a bit verbose but is more clear. I also fixed escaping, it seems to have been wrong wrt to `\` and `.`.
```suggestion
  private val nameIllegalCharRegex: Regex = """[^\p{L}0-9 _.:/%&#=\\+\-@]""".r
```

2022-04-14 07:14 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private val keyRegex: Regex = """[^A-Za-z0-9_]""".r
```suggestion
  private val keyIllegalCharRegex: Regex = """[^A-Za-z0-9_]""".r
```

2022-04-14 07:14 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +    ChronoUnit.MICROS.between(Instant.EPOCH, i).toDouble / 1000000
```suggestion
    ChronoUnit.MICROS.between(Instant.EPOCH, i).toDouble / 1000_000
```

2022-04-14 07:14 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +import cats.effect.{Clock, Ref}
```suggestion
import cats.effect.kernel.{Clock, Ref}
```

2022-04-14 07:15 UTC, catostrophe commented
@mrdziuban let's wait for the changes in t4c-core. We will cut a snapshot release and you can proceed with it.

2022-04-14 12:37 UTC, mrdziuban commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private val nameRegex: Regex = """[^\p{L}0-9 _\.:/%&#=\+\-@]""".r
I think `nameIllegalCharRegex` actually sounds like the opposite of what this is doing -- the `^` directly after `[` indicates that the regex will match any characters *except* the ones listed here. How does `nameAllowedCharRegex` sound instead?

Re: escaping, I wasn't trying to include `\` in the list of characters, I was just escaping `.` and `+`, but I think it's unnecessary within `[]`, so I can remove them. My suggestion is:

```suggestion
  private val nameAllowedCharRegex: Regex = """[^\p{L}0-9 _.:/%&#=+\-@]""".r
```

2022-04-14 12:37 UTC, mrdziuban commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private val keyRegex: Regex = """[^A-Za-z0-9_]""".r
Same as above, this regex will match all characters except the patterns listed here. How about this?

```suggestion
  private val keyAllowedCharRegex: Regex = """[^A-Za-z0-9_]""".r
```

2022-04-14 14:12 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private val nameRegex: Regex = """[^\p{L}0-9 _\.:/%&#=\+\-@]""".r
Yes, this regex matches any character except for those listed in `[ ]`, i.e. _special_ characters that _cannot_ be part of a name. Hence it's a list of illegal characters. Right?

2022-04-14 14:14 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private val nameRegex: Regex = """[^\p{L}0-9 _\.:/%&#=\+\-@]""".r
Re: escaping

> name – The logical name of the service that handled the request, up to 200 characters. For example, your application's name or domain name. Names can contain Unicode letters, numbers, and whitespace, and the following symbols: _, ., :, /, %, &, #, =, +, \\, -, @

As you see `\` should be in the list.

2022-04-14 15:55 UTC, mrdziuban commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private val nameRegex: Regex = """[^\p{L}0-9 _\.:/%&#=\+\-@]""".r
Thanks, I had missed that. And I don't feel strongly about the names, so updated to use `*IllegalChar*`

2022-04-14 19:10 UTC, catostrophe commented
You can use v0.13.1+12-491cff7e

2022-04-25 05:42 UTC, catostrophe commented
With the recent changes in trace4cats, the generator for TraceId in `trace4cats-xray` may look as follows:
```scala
object xray extends XRayCompatInstances0

trait XRayCompatInstances0 extends XRayCompatInstances1 {
  implicit def fromRandomClockTraceIdGen[F[_]: Apply: Random: Clock]: TraceId.Gen[F] = TraceId.Gen.from {
    val timeSize = Integer.BYTES
    val rndSize = TraceId.size - timeSize
    (Clock[F].realTime, Random[F].nextBytes(rndSize)).mapN { (t, r) =>
      val bytes = ByteBuffer.allocate(TraceId.size).putInt(t.toSeconds.toInt).put(r).array
      TraceId.unsafe(bytes)
    }
  }
}

trait XRayCompatInstances1 { this: XRayCompatInstances0 =>
  implicit def fromSyncTraceIdGen[F[_]: Sync]: TraceId.Gen[F] = {
    implicit val rnd: Random[F] = Random.javaUtilConcurrentThreadLocalRandom[F]
    fromRandomClockTraceIdGen[F]
  }
}

// maybe use different name
def toHex(traceId: TraceId): String = {
  val timeSize = Integer.BYTES
  val rndSize = TraceId.size - timeSize
  val arr = traceId.value
  val t = new String(Hex.encodeHex(arr, 0, timeSize, true))
  val r = new String(Hex.encodeHex(arr, timeSize, rndSize, true))
  s"1-$t-$r"
}
```

2022-04-25 06:04 UTC, catostrophe commented
Please use v0.13.1+16-78f06e87

2022-04-25 06:05 UTC, catostrophe commented
@mrdziuban do you have any blockers that prevent you from proceeding with this PR?

2022-04-26 13:49 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayExceptionId.scala
> +case class XRayExceptionId private (value: Array[Byte]) extends AnyVal {
Just copied `TraceId` from `model`

2022-04-26 13:49 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +  private def spanStatusFaultJson[F[_]: Applicative: XRayExceptionId.Gen](status: SpanStatus): F[JsonObject] =
Requires `XRayExceptionId.Gen` (which is autoderivable) instead of `Random`

2022-04-26 13:49 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +        "trace_id" := xRayTraceIdExportShow.show(span.context.traceId),
Explicitly use an alternative `Show` instance

2022-04-26 13:49 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +        "trace_id" := xRayTraceIdExportShow.show(span.context.traceId),
Use `traceId` direct from the span

2022-04-26 13:49 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/compat/explicits.scala
> +  def xRayTraceIdGen[F[_]: Apply: Random: Clock]: TraceId.Gen[F] = TraceId.Gen.from {
Alternative generator of `traceId` that is compatible with the rest `trace4cats` integrations.

2022-04-26 13:52 UTC, mrdziuban commented
@catostrophe I don't have any blockers other than time, work and life got in the way of me being able to commit time to this. Feel free to take it from here if you'd like, otherwise I can circle back to it when I have time (though I can't say for sure when that might be)

2022-04-26 13:55 UTC, catostrophe commented
@mrdziuban I just pushed some changes related to traceId generation. Next, I will ask you some questions regarding the implementation. Take your time, we're not in a hurry.

2022-04-26 17:13 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +    ChronoUnit.MICROS.between(Instant.EPOCH, i).toDouble / 1000000
Oh, this doesn't work on scala 2.12

2022-04-26 17:18 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpan.scala
> +    childSpans: Ref[F, Map[TraceId, NonEmptyList[CompletedSpan]]]
As I saw in the docs, child spans can be sent prior to the parent if they are typed as "subsegment". Is it possible when the parent is not yet sent, even as "in_progress"?

2022-04-26 17:18 UTC, catostrophe commented on modules/xray-udp-exporter/src/main/scala/io/janstenpickle/trace4cats/xray/XRayUdpSpanExporter.scala
> +            Deferred[F, IpAddress].flatMap { ipRef =>
Why do we need to resolve `IpAddress` every time we send another batch? This is not what we do in other implementations.

2025-10-09 15:54 UTC, mrdziuban commented
Hi @catostrophe and @janstenpickle, I never found the time (or need) to revisit and finish this implementation, so I'm going to close the PR. Feel free to pick it back up if you'd like, or if any other users are requesting X-Ray support.

2025-10-09 15:54 UTC, closed without merging